# Generated by Django 2.2.3 on 2019-07-24 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('export_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('tipo', models.CharField(choices=[('PARTICULAR', 'PARTICULAR'), ('FISCAL', 'FISCAL'), ('CASA MATRIZ', 'CASA MATRIZ'), ('COMERCIAL', 'COMERCIAL')], default='FISCAL', max_length=15, null=True)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=6)),
                ('piso', models.CharField(max_length=3, verbose_name='Piso')),
                ('departamento', models.CharField(max_length=3, verbose_name='Dpto')),
                ('otro', models.CharField(max_length=50, verbose_name='Datos Adicionales')),
                ('barrio', models.CharField(max_length=50, verbose_name='Barrio')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad/localidad')),
                ('partido', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=50)),
                ('Pais', models.CharField(default='Argentina', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
