# Generated by Django 2.2.3 on 2019-07-24 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('export_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('apellidos', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(max_length=50)),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono Celular')),
                ('telefono_aux', models.CharField(max_length=15, verbose_name='Telefono Alternativo')),
                ('nro_socio', models.CharField(max_length=10)),
                ('domicilio_particular', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='socios.Domicilio')),
            ],
            options={
                'verbose_name_plural': 'Socios',
                'verbose_name': 'Socio',
            },
        ),
    ]
