# Generated by Django 2.2.3 on 2019-07-25 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_socios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='Pais',
        ),
        migrations.AddField(
            model_name='socios',
            name='categoria',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socios',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socios',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socios',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='nro_socio',
            field=models.CharField(max_length=10, verbose_name='Numero de Socio'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='tipo_documento',
            field=models.CharField(max_length=10),
        ),
    ]
