# Generated by Django 2.2.4 on 2020-03-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_auto_20191205_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad_tickets',
            field=models.IntegerField(default=0, verbose_name='Cantidad de tickets'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='monto_total',
            field=models.FloatField(default=0, verbose_name='Monto Total'),
            preserve_default=False,
        ),
    ]
